version: '3.8'
services:
  cliparr:
    image: ghcr.io/redeyeredline/cliparr:latest
    container_name: cliparr
    restart: unless-stopped
    ports:
      - "8484:8484"
    volumes:
      - /opt/dockerdata/cliparr/data:/app/data
      - /opt/slowerdrive/media:/media:ro
    environment:
      - PORT=8484
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8484/health/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
