version: '3.8'

services:
  cliparr:
    # Choose the image variant that matches your host capabilities:
    # - CPU-only: ghcr.io/redeyeredline/cliparr:latest
    # - NVIDIA (CUDA/NVENC): ghcr.io/redeyeredline/cliparr:nvidia
    image: ghcr.io/redeyeredline/cliparr:nvidia
    container_name: cliparr
    restart: unless-stopped
    ports:
      - "8484:8484"
    volumes:
      # App data directory (database, logs, temp files)
      # Change this to your preferred data location
      - /opt/dockerdata/cliparr/data:/app/data
      # Media files - CHANGE THIS to your media directory
      - /opt/dockerdata/media:/media
    environment:
      - PORT=8484
    # NVIDIA runtime (uncomment if you have NVIDIA GPU)
    deploy:
     resources:
       reservations:
          devices:
           - driver: nvidia
             count: all
             capabilities: [gpu]
    # Device mapping for hardware acceleration (uncomment if needed)
    devices:
      - /dev/dri:/dev/dri
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8484/health/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 