version: '3.8'
services:
  cliparr:
    image: ghcr.io/redeyeredline/cliparr:latest   # <-- pre-built image pushed from CI
    container_name: cliparr
    restart: unless-stopped

    # --- networking ---
    ports:
      - "8484:8484"          # HTTP / WebSocket

    # --- persistent volumes ---
    volumes:
      # App data directory (database, logs, temp files)
      - /opt/dockerdata/cliparr/data:/app/data
      # Media files (read-only)
      - /opt/slowerdrive/media:/media:ro

    # --- runtime environment ---
    environment:
      - PORT=8484
      - NVIDIA_VISIBLE_DEVICES=all        # comment if no GPU
      - NVIDIA_DRIVER_CAPABILITIES=all    # comment if no GPU

    # GPU access (uncomment / tweak for your HW)
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8484/health/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s