version: "3.8"

services:
  cliparr:
    build: .
    container_name: cliparr
    ports:
      - "8484:8484"
    environment:
      - CLIPARR_IMPORT_MODE=import
    volumes:
      - /opt/slowerdata/media:/media
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
