version: "3.8"

services:
  cliparr:
    build: .
    container_name: cliparr
    ports:
      - "8484:8484"
    environment:
      - SONARR_URL=${SONARR_URL}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - CLIPARR_IMPORT_MODE=import
    volumes:
      - /opt/slowerdata/media:/media
      - /opt/dockerdata/cliparr:/opt/dockerdata/cliparr
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cliparr
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password

volumes:
  postgres_data:
    driver: local

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
