version: '3.8'

services:
  cliparr:
    container_name: cliparr
    build: .
    ports:
      - "8484:8484"
    volumes:
      - /opt/dockerdata/cliparr:/data
    environment:
      - NODE_ENV=production
      - PORT=8484
    restart: unless-stopped 