version: '3.8'

services:
  cliparr:
    container_name: cliparr
    build:
    context: .
    dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SONARR_URL=your_sonarr_url
      - SONARR_API_KEY=your_sonarr_api_key
      - CLIPARR_IMPORT_MODE=none  # Options: auto, import, none (default: none)
    volumes:
      # Database files
      - /path/to/data:/data
      # Media files as mapped in sonarr
      - /path/to/media:/media 