name: "Build and Publish Docker image (DISABLED)"

# This workflow is disabled to prevent tag conflicts
# All Docker builds are now handled by docker-build.yml
on:
  # No triggers - workflow is disabled
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled
        run: |
          echo "This workflow has been disabled in favor of docker-build.yml"
          echo "to prevent tag conflicts and ensure proper NVIDIA tag publishing."
          echo "The docker-build.yml workflow now handles all Docker image building"
          echo "with proper tag management for both latest and nvidia variants."
